#cloud-config

runcmd:
 - sudo mkdir /data
 - sudo chown azureuser -R /data
 - sudo apt update
 - sudo sed -i -e '55aazureuser        soft    nofile          65536' /etc/security/limits.conf
 - sudo sed -i -e '56aazureuser        hard    nofile          65536' /etc/security/limits.conf
 - sudo sed -i '2 i 127.0.0.1 automategisweb.westeurope.cloudapp.azure.com' /etc/hosts
 - sudo apt install authbind
 - sudo mkdir /etc/authbind
 - sudo mkdir /etc/authbind/byport
 - sudo touch /etc/authbind/byport/443
 - 'sudo chown azureuser: /etc/authbind/byport/443'
 - sudo chmod 777 /etc/authbind/byport/443
 - sudo touch /etc/authbind/byport/80
 - 'sudo chown azureuser: /etc/authbind/byport/80'
 - sudo chmod 777 /etc/authbind/byport/80
#  - sudo sed -i '1 i AUTHBIND=true' /etc/authbind/byport/80
#  - sudo sed -i '1 i AUTHBIND=true' /etc/authbind/byport/443
 - sudo echo "AUTHBIND=true" > /etc/authbind/byport/80
 - sudo echo "AUTHBIND=true" > /etc/authbind/byport/443
