#cloud-config

runcmd:
 - sudo mkdir /data
 - sudo chown azureuser -R /data
 - sudo apt update
 - sudo /sbin/sysctl -w vm.max_map_count=262144
 - sudo /sbin/sysctl -w vm.swappiness=1
 - sudo sed -i -e '55aazureuser        soft    nofile          65536' /etc/security/limits.conf
 - sudo sed -i -e '56aazureuser        hard    nofile          65536' /etc/security/limits.conf
